#!/bin/sh

# check for Download Enter stage
if test -f /data/mender/Download-Enter; then
    exit 21
fi

if [[ -f /data/mender/preserved-files.tgz ]]; then 
	tar -C / -xzf /data/mender/preserved-files.tgz
	rm /data/mender/preserved-files.tgz
fi

/opt/influx/wlan0.sh 

FLAG=$(ps | grep -c 'mender-connect')
if [ $FLAG -eq 1 ]; then
	/opt/influx/mender_client_start.sh && /usr/bin/mender check-update
fi 
