#!/bin/sh

#cp /data/mender/wpa_supplicant.conf /etc/wpa_supplicant.conf 
#cp /data/mender/mender.conf /etc/mender/mender.conf 

# start wlan communication
/sbin/ifconfig wlan0 up
if test -f /var/run/wpa_supplicant/wlan0; then
    rm /var/run/wpa_supplicant/wlan0
fi
/usr/sbin/wpa_supplicant -B -i wlan0 -D wext -c /etc/wpa_supplicant.conf > /dev/null
/sbin/dhclient wlan0 > /dev/null

sleep 2
FLAG=$(/sbin/ifconfig wlan0 | grep 'inet addr:' | cut -d: -f2)
if [[ $FLAG != "" ]]; then
        /opt/influx/mender_client_start.sh
	/usr/bin/mender  check-update
echo "Artifact Install Leave" >> /data/mender/log
	exit 0
fi

echo "Artifact Install Leave Wait" >> /data/mender/log
exit 21