#!/bin/sh

# check for Download Enter stage
if test -f /data/mender/Download-Enter; then
	ping -I wlan0 -q -c5 8.8.8.8 > /dev/null
	if [[ $? -ne 0 ]]; then
		# start wlan communication
		/sbin/ifconfig wlan0 up
		rm /var/run/wpa_supplicant/wlan0
		/usr/sbin/wpa_supplicant -B -i wlan0 -D wext -c /etc/wpa_supplicant.conf 
		/sbin/dhclient wlan0 
	fi
	exit 21	
fi 

ping -I wlan0 -q -c5 8.8.8.8 > /dev/null
if [[ $? -eq 0 ]]; then
	exit 21
fi

cp /data/mender/wpa_supplicant.conf /etc/wpa_supplicant.conf
rm /data/mender/wpa_supplicant.conf
cp /data/mender/mender.conf /etc/mender/mender.conf
rm /data/mender/mender.conf

#/opt/influx/mender_client_start.sh
#/bin/sleep 3

# start wlan communication
/sbin/ifconfig wlan0 up
#if test -f /var/run/wpa_supplicant/wlan0; then
    rm /var/run/wpa_supplicant/wlan0
#fi
/usr/sbin/wpa_supplicant -B -i wlan0 -D wext -c /etc/wpa_supplicant.conf 
/sbin/dhclient wlan0 

FLAG=$(/sbin/ifconfig wlan0 | grep 'inet addr:' | cut -d: -f2)
if [[ $FLAG == "" ]]; then
	exit 21
fi

/opt/influx/mender_client_start.sh
exit 0
