#!/bin/sh

# start wlan communication
/sbin/ifconfig wlan0 up
if test -f /var/run/wpa_supplicant/wlan0; then
    rm /var/run/wpa_supplicant/wlan0
fi
/usr/sbin/wpa_supplicant -B -i wlan0 -D wext -c /etc/wpa_supplicant.conf > /dev/null
/sbin/dhclient wlan0 > /dev/null

sleep 2
FLAG=$(/sbin/ifconfig wlan0 | grep 'inet addr:' | cut -d: -f2)
if [[ $FLAG != "" ]]; then
        /opt/influx/mender_client_start.sh
	/usr/bin/mender  check-update
	echo "Artifact Reboot Leave" >> /data/mender/log
	exit 0
fi

echo "Artifact Reboot Leave Wait" >> /data/mender/log
exit 21

#cp /data/mender/download /home/root/download

# add some cron jobs
#EDITOR=nano     # crontab uses this editor
#CRON_JOB="@reboot /opt/influx/wlan_config.sh"
#RESULT=$(/usr/bin/crontab -l -u root | grep "$CRON_JOB")
#if [[ $RESULT == "" ]]; then
#        /usr/bin/crontab -u root -l | { cat; echo "$CRON_JOB"; } | /usr/bin/crontab -
#fi
#RESULT=$(/usr/bin/crontab -l -u root | grep "/opt/influx/wlan_config.sh" | grep -v "@reboot /opt/influx/wlan_config.sh")
#if [[ $RESULT == "" ]]; then
#        /usr/bin/crontab -u root -l | { cat; echo "*/2 * * * * /opt/influx/wlan_config.sh"; } |  /usr/bin/crontab -
#fi

# trying to set up WIFI
#ifconfig wlan0 down
#/opt/influx/wlan_config.sh